// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://efqdvfqyegetrekukfqw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVmcWR2ZnF5ZWdldHJla3VrZnF3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY1MzEzNTEsImV4cCI6MjA1MjEwNzM1MX0.PoVDvinvU4FNmByqs5iCFy_eCe0Ac_QrjywW8TajtpM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);